# Generated by Django 6.1 on 2026-08-15 01:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Scenario', max_length=255)),
                ('purpose', models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance')], default='purchase', max_length=20)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fico_band', models.CharField(blank=True, choices=[('760+', '760+'), ('740-759', '740-759'), ('720-739', '720-739'), ('700-719', '700-719'), ('680-699', '680-699'), ('660-679', '660-679'), ('640-659', '640-659'), ('620-639', '620-639'), ('580-619', '580-619'), ('<580', '<580')], default='760+', max_length=20, null=True)),
                ('occupancy', models.CharField(choices=[('primary', 'Primary Residence'), ('second_home', 'Second Home'), ('investment', 'Investment Property')], default='primary', max_length=20)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('condo', 'Condo'), ('townhome', 'Townhome'), ('multi_unit', 'Multi-Unit (2-4)')], default='single_family', max_length=20)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('county_fips', models.CharField(blank=True, max_length=10, null=True)),
                ('program', models.CharField(choices=[('conventional', 'Conventional'), ('fha', 'FHA'), ('va', 'VA'), ('usda', 'USDA')], default='conventional', max_length=20)),
                ('term_months', models.PositiveIntegerField(default=360)),
                ('expected_horizon_months', models.PositiveIntegerField(default=84)),
                ('gross_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recurring_monthly_debts', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_property_tax_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_homeowners_insurance_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_hoa_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scenario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenchmarkPointModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=50)),
                ('observed_on', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'benchmark_point',
                'ordering': ['-observed_on'],
                'unique_together': {('series', 'observed_on')},
            },
        ),
        migrations.CreateModel(
            name='LoanOptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Entry'), ('loan_estimate', 'Transcribed Loan Estimate')], default='manual', max_length=20)),
                ('entered_on', models.DateField(default=django.utils.timezone.now)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('apr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('term_months', models.PositiveIntegerField(default=360)),
                ('points_pct', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('lender_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lender_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_mi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upfront_mi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_options', to='web.scenariomodel')),
            ],
            options={
                'db_table': 'loan_option',
                'ordering': ['created_at'],
            },
        ),
    ]
