# Generated by Django 6.1 on 2026-08-15 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_loanoptionmodel_apr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateApiBudgetModel',
            fields=[
                ('month_key', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('monthly_limit', models.PositiveIntegerField(default=20)),
                ('safety_threshold', models.PositiveIntegerField(default=18)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rate_api_budget',
            },
        ),
        migrations.CreateModel(
            name='RateApiCacheModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('query_state', models.CharField(max_length=10)),
                ('query_intent', models.CharField(max_length=20)),
                ('query_amount_bucket', models.PositiveIntegerField()),
                ('query_term_months', models.PositiveIntegerField()),
                ('response_payload', models.JSONField()),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'rate_api_cache',
                'ordering': ['-cached_at'],
            },
        ),
        migrations.AddField(
            model_name='loanoptionmodel',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='loanoptionmodel',
            name='external_reference_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanoptionmodel',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanoptionmodel',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('loan_estimate', 'Transcribed Loan Estimate'), ('rate_api', 'RateAPI Market Offer')], default='manual', max_length=20),
        ),
    ]
