# Generated by Django 6.1 on 2026-08-15 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rateapibudgetmodel_rateapicachemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateApiSnapshotModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lender', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, default='CA', max_length=10)),
                ('product_type', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('loan_program', models.CharField(default='conventional', max_length=50)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('apr', models.DecimalField(decimal_places=3, max_digits=6)),
                ('points', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('observed_on', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eligibility_summary', models.TextField(blank=True, default='')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'rate_api_snapshot',
                'ordering': ['-observed_on', 'rate'],
                'unique_together': {('lender', 'product_type', 'state', 'observed_on')},
            },
        ),
    ]
