# Generated by Django 6.1 on 2026-08-16 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rateapisnapshotmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='annual_appreciation_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0300'), help_text='Estimated annual home price appreciation rate (e.g. 0.0300 for 3%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='filing_status',
            field=models.CharField(choices=[('single', 'Single ($14,600 Standard)'), ('married_joint', 'Married Filing Jointly ($29,200 Standard)')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='itemize_deductions',
            field=models.BooleanField(default=False, help_text='Whether borrower itemizes tax deductions rather than taking the standard deduction'),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='marginal_tax_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.2400'), help_text='Combined federal + state marginal income tax bracket (e.g. 0.2400 for 24%)', max_digits=5, null=True),
        ),
    ]
