# Generated by Django 6.1 on 2026-08-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_scenariomodel_annual_appreciation_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariomodel',
            name='filing_status',
            field=models.CharField(blank=True, choices=[('single', 'Single ($14,600 Standard)'), ('married_joint', 'Married Filing Jointly ($29,200 Standard)')], default='single', max_length=20),
        ),
    ]
